include = ["app/**/*.py"]

line-length = 100

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[lint]
select = ["E", "F", "FAST", "I", "N", "W"]
ignore = ["COM812", "E401", "E501", "E711"]
