"""Added base models for event management

Revision ID: 014b3fbf54ad
Revises: c8585f9b0f2f
Create Date: 2026-03-14 19:39:35.788306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014b3fbf54ad'
down_revision: Union[str, Sequence[str], None] = 'c8585f9b0f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('org_unique_name', sa.String(), nullable=False),
    sa.Column('org_display_name', sa.String(), nullable=False),
    sa.Column('org_head_user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['org_head_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('org_id'),
    sa.UniqueConstraint('org_display_name')
    )
    op.create_index(op.f('ix_orgs_org_id'), 'orgs', ['org_id'], unique=False)
    op.create_index(op.f('ix_orgs_org_unique_name'), 'orgs', ['org_unique_name'], unique=True)
    op.create_table('events',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('event_org_id', sa.BigInteger(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('event_safe_name', sa.String(), nullable=False),
    sa.Column('event_suffix', sa.String(), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=False),
    sa.Column('event_location', sa.String(), nullable=False),
    sa.Column('event_application_info', sa.Text(), nullable=False),
    sa.Column('event_application_accept_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_application_accept_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_publication_status', sa.Enum('DRAFT', 'PUBLIC', name='eventpublicationstatus'), nullable=False),
    sa.CheckConstraint("event_publication_status = 'DRAFT' OR (event_description IS NOT NULL AND event_location IS NOT NULL AND event_application_info IS NOT NULL AND event_application_accept_start IS NOT NULL AND event_application_accept_end IS NOT NULL)", name='check_public_event_completeness'),
    sa.CheckConstraint('event_application_accept_start < event_application_accept_end', name='check_valid_application_date'),
    sa.ForeignKeyConstraint(['event_org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=False)
    op.create_table('org_members',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'JOINED', name='organizermemberstatus'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'org_id')
    )
    op.create_index(op.f('ix_org_members_org_id'), 'org_members', ['org_id'], unique=False)
    op.create_index(op.f('ix_org_members_user_id'), 'org_members', ['user_id'], unique=False)
    op.create_table('event_days',
    sa.Column('eventday_id', sa.BigInteger(), nullable=False),
    sa.Column('belong_in_event_id', sa.BigInteger(), nullable=False),
    sa.Column('eventday_date', sa.Date(), nullable=False),
    sa.Column('eventday_time_start', sa.Time(), nullable=False),
    sa.Column('eventday_time_end', sa.Time(), nullable=False),
    sa.Column('eventday_timezone', sa.String(), nullable=False),
    sa.CheckConstraint('eventday_time_start < eventday_time_end', name='check_eventday_times_valid'),
    sa.ForeignKeyConstraint(['belong_in_event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('eventday_id')
    )
    op.create_index(op.f('ix_event_days_eventday_id'), 'event_days', ['eventday_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_days_eventday_id'), table_name='event_days')
    op.drop_table('event_days')
    op.drop_index(op.f('ix_org_members_user_id'), table_name='org_members')
    op.drop_index(op.f('ix_org_members_org_id'), table_name='org_members')
    op.drop_table('org_members')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_orgs_org_unique_name'), table_name='orgs')
    op.drop_index(op.f('ix_orgs_org_id'), table_name='orgs')
    op.drop_table('orgs')
    # ### end Alembic commands ###
