"""Hot fix 2

Revision ID: 0664e6e25499
Revises: af54e123ef63
Create Date: 2026-03-27 05:30:58.469899

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0664e6e25499"
down_revision: Union[str, Sequence[str], None] = "af54e123ef63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_constraint("check_public_event_completeness", "events", type_="check")
    op.create_check_constraint(
        "check_public_event_completeness",
        "events",
        "event_publication_status = 'DRAFT' OR "
        "(event_description != '' AND "
        "event_location != '' AND "
        "event_application_info != '' AND "
        "event_map_img_suffix IS NOT NULL AND "
        "event_map_data_suffix IS NOT NULL)",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
