"""Add Event Applications

Revision ID: 17fce120f573
Revises: f7a1f4e4772d
Create Date: 2026-03-26 23:39:40.864436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17fce120f573'
down_revision: Union[str, Sequence[str], None] = 'f7a1f4e4772d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_applications',
    sa.Column('app_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_booth', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_index(op.f('ix_event_applications_app_id'), 'event_applications', ['app_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_applications_app_id'), table_name='event_applications')
    op.drop_table('event_applications')
    # ### end Alembic commands ###
