"""Added profile picture suffix to DB

Revision ID: c8585f9b0f2f
Revises: 9b58785b1c94
Create Date: 2026-03-09 02:21:23.091879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8585f9b0f2f'
down_revision: Union[str, Sequence[str], None] = '9b58785b1c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_pfp_suffix', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_pfp_suffix')
    # ### end Alembic commands ###
