"""Update event to have map related data.

Revision ID: f7a1f4e4772d
Revises: 014b3fbf54ad
Create Date: 2026-03-26 21:26:14.411870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a1f4e4772d'
down_revision: Union[str, Sequence[str], None] = '014b3fbf54ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_map_img_suffix', sa.String(), nullable=True))
    op.add_column('events', sa.Column('event_map_data_suffix', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'event_map_data_suffix')
    op.drop_column('events', 'event_map_img_suffix')
    # ### end Alembic commands ###
